### ISSUE TITLE
preflight_check conditioned does not tally with message

### ISSUE THREAD

**Issue by Freemanlabs** [RasaHQ/REI#32]
I am trying to update my rasa x from 0.42.x to the latest (on my local PC). From the documentation, it seems REI is the advised method. 

In `rei.sh`, the condition specified in the below code block does not tally with the error message.

I tried and tried until I had to open the shell script.
Or is it just me that feels it's an error?

```
if [[ $freedisk -lt 20 ]]; then
       error "We have only ${diskfree} GB of Free Disk which is not enough to Run RASA X / RASA OSS"
       error "Please free at least 8 GB of local disk and run the script again"
       exit 1
    fi;
```
and
```
    if [[ $freemem -lt 6 ]]; then
       error "We have only ${freemem} GB of Free Memory which is not enough to Run RASA X / RASA OSS"
       error "Please free at least 8 GB of local memory and run the script again"
       exit 1
    fi;
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @mvielkind will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by RASADSA** [comment]
Hello @Freemanlabs 👋 

REI is only setting up your local environment for rasactl - the update to a newer version of RASA X doesnt invoke REI you only need rasactl.

**Comment by Freemanlabs** [comment]
Thanks @RASADSA 
So, if I don't need REI, how do I use rasactl to update and spin up RASA X since rasa 3.0 doesn't work with rasa X 0.42.x and below?

Couldn't find docs for that
