### ISSUE TITLE
Variable mismatch (freedisk instead of diskfree

### ISSUE THREAD

**Issue by Freemanlabs** [RasaHQ/REI#33]
in `rei.sh` (preflight_check()), the error message for disk space shows as the following on my PC:

`We have only  GB of Free Disk which is not enough to Run RASA X / RASA OSS`
You would see it doesn't specify how much space I have left.

On opening the file, I see you created a variable "freedisk" but specified "diskfree" in the message.

Please fix.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koernerfelicia will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by RASADSA** [comment]
@Freemanlabs 👋 
can you tell me which version of MacOS you are running ?

**Comment by Freemanlabs** [comment]
I am running a Linux OS.
However, I don't know if it's an issue with OS. Like I mentioned, in `rei.sh`, I see you created a variable "freedisk" but specified "diskfree" in the message.

**Comment by andreoid** [comment]
@Freemanlabs fix has now been merged 👍
