### ISSUE TITLE
Function code for Fedora (check_install_centos) is missing

### ISSUE THREAD

**Issue by arunabh09** [RasaHQ/REI#34]
Unable to use the rei.sh script on a Fedora based Linux distribution system as the function code for check_install_centos (line 553) is missing.

As a result, the script returns an error: "check_install_centos" command not found.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alopez will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by arunabh09** [comment]
Hi!
Just doing a post one month followup to see if we have any updates on fixing this bug.

**Comment by RASADSA** [comment]
Hello @arunabh09 
fix got merged for Fedora Desktop to main branch.
thanks for the bug report
cheers
